=begin
#VBASoftware

#APIs for VBASoftware

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vba::AmountDetailsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AmountDetailsApi' do
  before do
    # run before each test
    @api_instance = Vba::AmountDetailsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AmountDetailsApi' do
    it 'should create an instance of AmountDetailsApi' do
      expect(@api_instance).to be_instance_of(Vba::AmountDetailsApi)
    end
  end

  # unit tests for get_amount_details
  # Get AmountDetails
  # Gets AmountDetails
  # @param vbasoftware_database Target database
  # @param key Key
  # @param [Hash] opts the optional parameters
  # @return [AmountDetailsVBAResponse]
  describe 'get_amount_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_amount_details
  # List AmountDetails
  # Lists all AmountDetails
  # @param vbasoftware_database Target database
  # @param [Hash] opts the optional parameters
  # @return [AmountDetailsListVBAResponse]
  describe 'list_amount_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
