=begin
#VBASoftware

#APIs for VBASoftware

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vba::ClaimRepriceRemoveApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ClaimRepriceRemoveApi' do
  before do
    # run before each test
    @api_instance = Vba::ClaimRepriceRemoveApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClaimRepriceRemoveApi' do
    it 'should create an instance of ClaimRepriceRemoveApi' do
      expect(@api_instance).to be_instance_of(Vba::ClaimRepriceRemoveApi)
    end
  end

  # unit tests for create_claim_reprice_remove
  # Create ClaimRepriceRemove
  # Creates a new ClaimRepriceRemove
  # @param vbasoftware_database Target database
  # @param claim_reprice_remove 
  # @param [Hash] opts the optional parameters
  # @return [ClaimRepriceRemoveVBAResponse]
  describe 'create_claim_reprice_remove test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_claim_reprice_remove
  # Delete ClaimRepriceRemove
  # Deletes an ClaimRepriceRemove
  # @param vbasoftware_database Target database
  # @param claim_reprice_remove_key ClaimRepriceRemove Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_claim_reprice_remove test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_claim_reprice_remove
  # Get ClaimRepriceRemove
  # Gets ClaimRepriceRemove
  # @param vbasoftware_database Target database
  # @param claim_reprice_remove_key ClaimRepriceRemove Key
  # @param [Hash] opts the optional parameters
  # @return [ClaimRepriceRemoveVBAResponse]
  describe 'get_claim_reprice_remove test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_claim_reprice_remove
  # List ClaimRepriceRemove
  # Lists all ClaimRepriceRemove
  # @param vbasoftware_database Target database
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort_by Comma separated string to sort by. Each sort field can be followed by :asc or :desc to specify sort direction, ascending is default. E.g., &#39;Property1:desc,Property2:asc,Property3:asc&#39; sorts Property1 in descending order, Property2 in ascending, and Property3 in ascending.
  # @option opts [Integer] :page Page
  # @option opts [Integer] :page_size Page Size
  # @return [ClaimRepriceRemoveListVBAResponse]
  describe 'list_claim_reprice_remove test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_batch_claim_reprice_remove
  # Create or Update Batch ClaimRepriceRemove
  # Create or Update multiple ClaimRepriceRemove at once.  If the entity exists, it will be updated.  If the entity does not exist, it will be created.
  # @param vbasoftware_database Target database
  # @param claim_reprice_remove 
  # @param [Hash] opts the optional parameters
  # @return [MultiCodeResponseListVBAResponse]
  describe 'update_batch_claim_reprice_remove test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_claim_reprice_remove
  # Update ClaimRepriceRemove
  # Updates a specific ClaimRepriceRemove.
  # @param vbasoftware_database Target database
  # @param claim_reprice_remove_key ClaimRepriceRemove Key
  # @param claim_reprice_remove 
  # @param [Hash] opts the optional parameters
  # @return [ClaimRepriceRemoveVBAResponse]
  describe 'update_claim_reprice_remove test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
