=begin
#VBASoftware

#APIs for VBASoftware

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vba::CredentialingPracticeCategoriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CredentialingPracticeCategoriesApi' do
  before do
    # run before each test
    @api_instance = Vba::CredentialingPracticeCategoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CredentialingPracticeCategoriesApi' do
    it 'should create an instance of CredentialingPracticeCategoriesApi' do
      expect(@api_instance).to be_instance_of(Vba::CredentialingPracticeCategoriesApi)
    end
  end

  # unit tests for create_cred_practice_category
  # Create CredPracticeCategory
  # Creates a new CredPracticeCategory
  # @param vbasoftware_database Target database
  # @param cred_practice_category 
  # @param [Hash] opts the optional parameters
  # @return [CredPracticeCategoryVBAResponse]
  describe 'create_cred_practice_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_cred_practice_category
  # Delete CredPracticeCategory
  # Deletes an CredPracticeCategory
  # @param vbasoftware_database Target database
  # @param cred_practice_category_key CredPracticeCategory Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_cred_practice_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_cred_practice_category
  # Get CredPracticeCategory
  # Gets CredPracticeCategory
  # @param vbasoftware_database Target database
  # @param cred_practice_category_key CredPracticeCategory Key
  # @param [Hash] opts the optional parameters
  # @return [CredPracticeCategoryVBAResponse]
  describe 'get_cred_practice_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_cred_practice_category
  # List CredPracticeCategory
  # Lists all CredPracticeCategory
  # @param vbasoftware_database Target database
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page
  # @option opts [Integer] :page_size Page Size
  # @option opts [String] :sort_by Comma separated string to sort by. Each sort field can be followed by :asc or :desc to specify sort direction, ascending is default. E.g., &#39;Property1:desc,Property2:asc,Property3:asc&#39; sorts Property1 in descending order, Property2 in ascending, and Property3 in ascending.
  # @return [CredPracticeCategoryListVBAResponse]
  describe 'list_cred_practice_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_batch_cred_practice_category
  # Create or Update Batch CredPracticeCategory
  # Create or Update multiple CredPracticeCategory at once.  If the entity exists, it will be updated.  If the entity does not exist, it will be created.
  # @param vbasoftware_database Target database
  # @param cred_practice_category 
  # @param [Hash] opts the optional parameters
  # @return [MultiCodeResponseListVBAResponse]
  describe 'update_batch_cred_practice_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_cred_practice_category
  # Update CredPracticeCategory
  # Updates a specific CredPracticeCategory.
  # @param vbasoftware_database Target database
  # @param cred_practice_category_key CredPracticeCategory Key
  # @param cred_practice_category 
  # @param [Hash] opts the optional parameters
  # @return [CredPracticeCategoryVBAResponse]
  describe 'update_cred_practice_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
