=begin
#VBASoftware

#APIs for VBASoftware

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vba::DisasterLocationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DisasterLocationsApi' do
  before do
    # run before each test
    @api_instance = Vba::DisasterLocationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DisasterLocationsApi' do
    it 'should create an instance of DisasterLocationsApi' do
      expect(@api_instance).to be_instance_of(Vba::DisasterLocationsApi)
    end
  end

  # unit tests for create_disaster_location
  # Create DisasterLocation
  # Creates a new DisasterLocation
  # @param vbasoftware_database Target database
  # @param disaster_location 
  # @param [Hash] opts the optional parameters
  # @return [DisasterLocationVBAResponse]
  describe 'create_disaster_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_disaster_location
  # Delete DisasterLocation
  # Deletes an DisasterLocation
  # @param vbasoftware_database Target database
  # @param disaster_location_key DisasterLocation Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_disaster_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_disaster_location
  # Get DisasterLocation
  # Gets DisasterLocation
  # @param vbasoftware_database Target database
  # @param disaster_location_key DisasterLocation Key
  # @param [Hash] opts the optional parameters
  # @return [DisasterLocationVBAResponse]
  describe 'get_disaster_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_disaster_location
  # List DisasterLocation
  # Lists all DisasterLocation
  # @param vbasoftware_database Target database
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort_by Comma separated string to sort by. Each sort field can be followed by :asc or :desc to specify sort direction, ascending is default. E.g., &#39;Property1:desc,Property2:asc,Property3:asc&#39; sorts Property1 in descending order, Property2 in ascending, and Property3 in ascending.
  # @option opts [Integer] :page Page
  # @option opts [Integer] :page_size Page Size
  # @return [DisasterLocationListVBAResponse]
  describe 'list_disaster_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_batch_disaster_location
  # Create or Update Batch DisasterLocation
  # Create or Update multiple DisasterLocation at once.  If the entity exists, it will be updated.  If the entity does not exist, it will be created.
  # @param vbasoftware_database Target database
  # @param disaster_location 
  # @param [Hash] opts the optional parameters
  # @return [MultiCodeResponseListVBAResponse]
  describe 'update_batch_disaster_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_disaster_location
  # Update DisasterLocation
  # Updates a specific DisasterLocation.
  # @param vbasoftware_database Target database
  # @param disaster_location_key DisasterLocation Key
  # @param disaster_location 
  # @param [Hash] opts the optional parameters
  # @return [DisasterLocationVBAResponse]
  describe 'update_disaster_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
