=begin
#VBASoftware

#APIs for VBASoftware

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vba::FundingDepositsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FundingDepositsApi' do
  before do
    # run before each test
    @api_instance = Vba::FundingDepositsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FundingDepositsApi' do
    it 'should create an instance of FundingDepositsApi' do
      expect(@api_instance).to be_instance_of(Vba::FundingDepositsApi)
    end
  end

  # unit tests for add_funding_deposit
  # Add Funding to Deposit
  # Creates Funding items and attaches them to an existing Deposit.
  # @param vbasoftware_database Target database
  # @param deposit_key Deposit Key
  # @param funding 
  # @param [Hash] opts the optional parameters
  # @return [FundingDepositVBAResponse]
  describe 'add_funding_deposit test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_funding_deposit
  # Create FundingDeposit
  # Creates a new FundingDeposit
  # @param vbasoftware_database Target database
  # @param funding_deposit 
  # @param [Hash] opts the optional parameters
  # @return [FundingDepositVBAResponse]
  describe 'create_funding_deposit test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_funding_deposit
  # Delete FundingDeposit
  # Deletes an FundingDeposit
  # @param vbasoftware_database Target database
  # @param deposit_key Deposit Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_funding_deposit test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_funding_deposit
  # Get FundingDeposit
  # Gets FundingDeposit
  # @param vbasoftware_database Target database
  # @param deposit_key Deposit Key
  # @param [Hash] opts the optional parameters
  # @return [FundingDepositVBAResponse]
  describe 'get_funding_deposit test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_funding_deposit
  # List FundingDeposit
  # Lists all FundingDeposit
  # @param vbasoftware_database Target database
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page
  # @option opts [Integer] :page_size Page Size
  # @option opts [String] :sort_by Comma separated string to sort by. Each sort field can be followed by :asc or :desc to specify sort direction, ascending is default. E.g., &#39;Property1:desc,Property2:asc,Property3:asc&#39; sorts Property1 in descending order, Property2 in ascending, and Property3 in ascending.
  # @return [FundingDepositListVBAResponse]
  describe 'list_funding_deposit test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_batch_funding_deposit
  # Create or Update Batch FundingDeposit
  # Create or Update multiple FundingDeposit at once.  If the entity exists, it will be updated.  If the entity does not exist, it will be created.
  # @param vbasoftware_database Target database
  # @param funding_deposit 
  # @param [Hash] opts the optional parameters
  # @return [MultiCodeResponseListVBAResponse]
  describe 'update_batch_funding_deposit test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_funding_deposit
  # Update FundingDeposit
  # Updates a specific FundingDeposit.
  # @param vbasoftware_database Target database
  # @param deposit_key Deposit Key
  # @param funding_deposit 
  # @param [Hash] opts the optional parameters
  # @return [FundingDepositVBAResponse]
  describe 'update_funding_deposit test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for void_funding_deposit
  # Void FundingDeposit
  # Deletes an FundingDeposit entry and changes the associated Funding items back to unassigned (not part of any deposit).
  # @param vbasoftware_database Target database
  # @param deposit_key Deposit Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'void_funding_deposit test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
