=begin
#VBASoftware

#APIs for VBASoftware

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vba::FundingRequestStatusesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FundingRequestStatusesApi' do
  before do
    # run before each test
    @api_instance = Vba::FundingRequestStatusesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FundingRequestStatusesApi' do
    it 'should create an instance of FundingRequestStatusesApi' do
      expect(@api_instance).to be_instance_of(Vba::FundingRequestStatusesApi)
    end
  end

  # unit tests for create_funding_request_status
  # Create FundingRequestStatus
  # Creates a new FundingRequestStatus
  # @param vbasoftware_database Target database
  # @param funding_request_status 
  # @param [Hash] opts the optional parameters
  # @return [FundingRequestStatusVBAResponse]
  describe 'create_funding_request_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_funding_request_status
  # Delete FundingRequestStatus
  # Deletes an FundingRequestStatus
  # @param vbasoftware_database Target database
  # @param request_status Request Status
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_funding_request_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_funding_request_status
  # Get FundingRequestStatus
  # Gets FundingRequestStatus
  # @param vbasoftware_database Target database
  # @param request_status Request Status
  # @param [Hash] opts the optional parameters
  # @return [FundingRequestStatusVBAResponse]
  describe 'get_funding_request_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_funding_request_status
  # List FundingRequestStatus
  # Lists all FundingRequestStatus
  # @param vbasoftware_database Target database
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page
  # @option opts [Integer] :page_size Page Size
  # @option opts [String] :sort_by Comma separated string to sort by. Each sort field can be followed by :asc or :desc to specify sort direction, ascending is default. E.g., &#39;Property1:desc,Property2:asc,Property3:asc&#39; sorts Property1 in descending order, Property2 in ascending, and Property3 in ascending.
  # @return [FundingRequestStatusListVBAResponse]
  describe 'list_funding_request_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_batch_funding_request_status
  # Create or Update Batch FundingRequestStatus
  # Create or Update multiple FundingRequestStatus at once.  If the entity exists, it will be updated.  If the entity does not exist, it will be created.
  # @param vbasoftware_database Target database
  # @param funding_request_status 
  # @param [Hash] opts the optional parameters
  # @return [MultiCodeResponseListVBAResponse]
  describe 'update_batch_funding_request_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_funding_request_status
  # Update FundingRequestStatus
  # Updates a specific FundingRequestStatus.
  # @param vbasoftware_database Target database
  # @param request_status Request Status
  # @param funding_request_status 
  # @param [Hash] opts the optional parameters
  # @return [FundingRequestStatusVBAResponse]
  describe 'update_funding_request_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
