=begin
#VBASoftware

#APIs for VBASoftware

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vba::GroupFlexesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GroupFlexesApi' do
  before do
    # run before each test
    @api_instance = Vba::GroupFlexesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GroupFlexesApi' do
    it 'should create an instance of GroupFlexesApi' do
      expect(@api_instance).to be_instance_of(Vba::GroupFlexesApi)
    end
  end

  # unit tests for create_group_flex
  # Create GroupFlex
  # Creates a new GroupFlex
  # @param vbasoftware_database Target database
  # @param group_id Group ID
  # @param group_flex 
  # @param [Hash] opts the optional parameters
  # @return [GroupFlexVBAResponse]
  describe 'create_group_flex test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_group_flex
  # Delete GroupFlex
  # Deletes an GroupFlex
  # @param vbasoftware_database Target database
  # @param group_id Group ID
  # @param plan_id Plan ID
  # @param calendar_year Calendar Year
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_group_flex test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_group_flex
  # Get GroupFlex
  # Gets GroupFlex
  # @param vbasoftware_database Target database
  # @param group_id Group ID
  # @param plan_id Plan ID
  # @param calendar_year Calendar Year
  # @param [Hash] opts the optional parameters
  # @return [GroupFlexVBAResponse]
  describe 'get_group_flex test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_group_flex
  # List GroupFlex
  # Lists all GroupFlex for the given groupID
  # @param vbasoftware_database Target database
  # @param group_id Group ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page
  # @option opts [Integer] :page_size Page Size
  # @option opts [String] :sort_by Comma separated string to sort by. Each sort field can be followed by :asc or :desc to specify sort direction, ascending is default. E.g., &#39;Property1:desc,Property2:asc,Property3:asc&#39; sorts Property1 in descending order, Property2 in ascending, and Property3 in ascending.
  # @return [GroupFlexListVBAResponse]
  describe 'list_group_flex test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_batch_group_flex
  # Create or Update Batch GroupFlex
  # Create or Update multiple GroupFlex at once.  If the entity exists, it will be updated.  If the entity does not exist, it will be created.
  # @param vbasoftware_database Target database
  # @param group_id Group ID
  # @param group_flex 
  # @param [Hash] opts the optional parameters
  # @return [MultiCodeResponseListVBAResponse]
  describe 'update_batch_group_flex test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_group_flex
  # Update GroupFlex
  # Updates a specific GroupFlex.
  # @param vbasoftware_database Target database
  # @param group_id Group ID
  # @param plan_id Plan ID
  # @param calendar_year Calendar Year
  # @param group_flex 
  # @param [Hash] opts the optional parameters
  # @return [GroupFlexVBAResponse]
  describe 'update_group_flex test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
