=begin
#VBASoftware

#APIs for VBASoftware

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vba::PlanProcedureAgeRestrictionModifiersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PlanProcedureAgeRestrictionModifiersApi' do
  before do
    # run before each test
    @api_instance = Vba::PlanProcedureAgeRestrictionModifiersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PlanProcedureAgeRestrictionModifiersApi' do
    it 'should create an instance of PlanProcedureAgeRestrictionModifiersApi' do
      expect(@api_instance).to be_instance_of(Vba::PlanProcedureAgeRestrictionModifiersApi)
    end
  end

  # unit tests for create_plan_procedure_age_modifier
  # Create PlanProcedureAgeModifier
  # Creates a new PlanProcedureAgeModifier
  # @param vbasoftware_database Target database
  # @param plan_id Plan ID
  # @param procedure_age_key ProcedureAgeKey
  # @param plan_procedure_age_modifier 
  # @param [Hash] opts the optional parameters
  # @return [PlanProcedureAgeModifierVBAResponse]
  describe 'create_plan_procedure_age_modifier test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_plan_procedure_age_modifier
  # Delete PlanProcedureAgeModifier
  # Deletes an PlanProcedureAgeModifier
  # @param vbasoftware_database Target database
  # @param plan_id Plan ID
  # @param procedure_age_key ProcedureAgeKey
  # @param plan_procedure_age_modifier_key PlanProcedureAgeModifier Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_plan_procedure_age_modifier test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_plan_procedure_age_modifier
  # Get PlanProcedureAgeModifier
  # Gets PlanProcedureAgeModifier
  # @param vbasoftware_database Target database
  # @param plan_id Plan ID
  # @param procedure_age_key ProcedureAgeKey
  # @param plan_procedure_age_modifier_key PlanProcedureAgeModifier Key
  # @param [Hash] opts the optional parameters
  # @return [PlanProcedureAgeModifierVBAResponse]
  describe 'get_plan_procedure_age_modifier test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_plan_procedure_age_modifier
  # List PlanProcedureAgeModifier
  # Lists all PlanProcedureAgeModifier for the given procedureAgeKey
  # @param vbasoftware_database Target database
  # @param plan_id Plan ID
  # @param procedure_age_key ProcedureAgeKey
  # @param [Hash] opts the optional parameters
  # @return [PlanProcedureAgeModifierListVBAResponse]
  describe 'list_plan_procedure_age_modifier test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_batch_plan_procedure_age_modifier
  # Create or Update Batch PlanProcedureAgeModifier
  # Create or Update multiple PlanProcedureAgeModifier at once.  If the entity exists, it will be updated.  If the entity does not exist, it will be created.
  # @param vbasoftware_database Target database
  # @param plan_id Plan ID
  # @param procedure_age_key ProcedureAgeKey
  # @param plan_procedure_age_modifier 
  # @param [Hash] opts the optional parameters
  # @return [MultiCodeResponseListVBAResponse]
  describe 'update_batch_plan_procedure_age_modifier test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_plan_procedure_age_modifier
  # Update PlanProcedureAgeModifier
  # Updates a specific PlanProcedureAgeModifier.
  # @param vbasoftware_database Target database
  # @param plan_id Plan ID
  # @param procedure_age_key ProcedureAgeKey
  # @param plan_procedure_age_modifier_key PlanProcedureAgeModifier Key
  # @param plan_procedure_age_modifier 
  # @param [Hash] opts the optional parameters
  # @return [PlanProcedureAgeModifierVBAResponse]
  describe 'update_plan_procedure_age_modifier test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
