=begin
#VBASoftware

#APIs for VBASoftware

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vba::SendToApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SendToApi' do
  before do
    # run before each test
    @api_instance = Vba::SendToApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SendToApi' do
    it 'should create an instance of SendToApi' do
      expect(@api_instance).to be_instance_of(Vba::SendToApi)
    end
  end

  # unit tests for create_send_to
  # Create SendTo
  # Creates a new SendTo
  # @param vbasoftware_database Target database
  # @param send_to 
  # @param [Hash] opts the optional parameters
  # @return [SendToVBAResponse]
  describe 'create_send_to test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_send_to
  # Delete SendTo
  # Deletes an SendTo
  # @param vbasoftware_database Target database
  # @param send_to_id SendTo ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_send_to test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_send_to
  # Get SendTo
  # Gets SendTo
  # @param vbasoftware_database Target database
  # @param send_to_id SendTo ID
  # @param [Hash] opts the optional parameters
  # @return [SendToVBAResponse]
  describe 'get_send_to test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_send_to
  # List SendTo
  # Lists all SendTo
  # @param vbasoftware_database Target database
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page
  # @option opts [Integer] :page_size Page Size
  # @option opts [String] :sort_by Comma separated string to sort by. Each sort field can be followed by :asc or :desc to specify sort direction, ascending is default. E.g., &#39;Property1:desc,Property2:asc,Property3:asc&#39; sorts Property1 in descending order, Property2 in ascending, and Property3 in ascending.
  # @return [SendToListVBAResponse]
  describe 'list_send_to test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_batch_send_to
  # Create or Update Batch SendTo
  # Create or Update multiple SendTo at once.  If the entity exists, it will be updated.  If the entity does not exist, it will be created.
  # @param vbasoftware_database Target database
  # @param send_to 
  # @param [Hash] opts the optional parameters
  # @return [MultiCodeResponseListVBAResponse]
  describe 'update_batch_send_to test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_send_to
  # Update SendTo
  # Updates a specific SendTo.
  # @param vbasoftware_database Target database
  # @param send_to_id SendTo ID
  # @param send_to 
  # @param [Hash] opts the optional parameters
  # @return [SendToVBAResponse]
  describe 'update_send_to test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
