=begin
#VBASoftware

#APIs for VBASoftware

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vba::SignaturesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SignaturesApi' do
  before do
    # run before each test
    @api_instance = Vba::SignaturesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SignaturesApi' do
    it 'should create an instance of SignaturesApi' do
      expect(@api_instance).to be_instance_of(Vba::SignaturesApi)
    end
  end

  # unit tests for create_signature
  # Create Signature
  # Creates a new Signature
  # @param vbasoftware_database Target database
  # @param signature 
  # @param [Hash] opts the optional parameters
  # @return [SignatureVBAResponse]
  describe 'create_signature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_signature
  # Delete Signature
  # Deletes an Signature
  # @param vbasoftware_database Target database
  # @param signature_key Signature Key
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_signature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_signature
  # Get Signature
  # Gets Signature
  # @param vbasoftware_database Target database
  # @param signature_key Signature Key
  # @param [Hash] opts the optional parameters
  # @return [SignatureVBAResponse]
  describe 'get_signature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_signature
  # List Signature
  # Lists all Signature
  # @param vbasoftware_database Target database
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page
  # @option opts [Integer] :page_size Page Size
  # @option opts [String] :sort_by Comma separated string to sort by. Each sort field can be followed by :asc or :desc to specify sort direction, ascending is default. E.g., &#39;Property1:desc,Property2:asc,Property3:asc&#39; sorts Property1 in descending order, Property2 in ascending, and Property3 in ascending.
  # @return [SignatureListVBAResponse]
  describe 'list_signature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_batch_signature
  # Create or Update Batch Signature
  # Create or Update multiple Signature at once.  If the entity exists, it will be updated.  If the entity does not exist, it will be created.
  # @param vbasoftware_database Target database
  # @param signature 
  # @param [Hash] opts the optional parameters
  # @return [MultiCodeResponseListVBAResponse]
  describe 'update_batch_signature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_signature
  # Update Signature
  # Updates a specific Signature.
  # @param vbasoftware_database Target database
  # @param signature_key Signature Key
  # @param signature 
  # @param [Hash] opts the optional parameters
  # @return [SignatureVBAResponse]
  describe 'update_signature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
