=begin
#VBASoftware

#APIs for VBASoftware

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Vba::PremRateAgeTypeVBAResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Vba::PremRateAgeTypeVBAResponse do
  let(:instance) { Vba::PremRateAgeTypeVBAResponse.new }

  describe 'test an instance of PremRateAgeTypeVBAResponse' do
    it 'should create an instance of PremRateAgeTypeVBAResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Vba::PremRateAgeTypeVBAResponse)
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "debug"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
