=begin
#VBASoftware

#APIs for VBASoftware

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Vba::VerifyMFADeviceSetupRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Vba::VerifyMFADeviceSetupRequest do
  let(:instance) { Vba::VerifyMFADeviceSetupRequest.new }

  describe 'test an instance of VerifyMFADeviceSetupRequest' do
    it 'should create an instance of VerifyMFADeviceSetupRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Vba::VerifyMFADeviceSetupRequest)
    end
  end

  describe 'test attribute "friendly_device_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "access_token"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "user_code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
