=begin
#VBASoftware

#APIs for VBASoftware

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'cgi'

module Vba
  class NetworksApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create Network
    # Creates a new Network
    # @param vbasoftware_database [String] Target database
    # @param networks [Networks] 
    # @param [Hash] opts the optional parameters
    # @return [NetworksVBAResponse]
    def create_network(vbasoftware_database, networks, opts = {})
      data, _status_code, _headers = create_network_with_http_info(vbasoftware_database, networks, opts)
      data
    end

    # Create Network
    # Creates a new Network
    # @param vbasoftware_database [String] Target database
    # @param networks [Networks] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(NetworksVBAResponse, Integer, Hash)>] NetworksVBAResponse data, response status code and response headers
    def create_network_with_http_info(vbasoftware_database, networks, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NetworksApi.create_network ...'
      end
      # verify the required parameter 'vbasoftware_database' is set
      if @api_client.config.client_side_validation && vbasoftware_database.nil?
        fail ArgumentError, "Missing the required parameter 'vbasoftware_database' when calling NetworksApi.create_network"
      end
      # verify the required parameter 'networks' is set
      if @api_client.config.client_side_validation && networks.nil?
        fail ArgumentError, "Missing the required parameter 'networks' when calling NetworksApi.create_network"
      end
      # resource path
      local_var_path = '/networks'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['text/plain', 'application/json', 'text/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'text/json', 'application/*+json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'vbasoftware-database'] = vbasoftware_database

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(networks)

      # return_type
      return_type = opts[:debug_return_type] || 'NetworksVBAResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKeyAuth', 'bearerAuth']

      new_options = opts.merge(
        :operation => :"NetworksApi.create_network",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NetworksApi#create_network\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Create or Update Batch Network
    # Creates or Updates multiple Networks
    # @param vbasoftware_database [String] Target database
    # @param networks [Array<Networks>] 
    # @param [Hash] opts the optional parameters
    # @return [MultiCodeResponseListVBAResponse]
    def create_or_update_batch_networks(vbasoftware_database, networks, opts = {})
      data, _status_code, _headers = create_or_update_batch_networks_with_http_info(vbasoftware_database, networks, opts)
      data
    end

    # Create or Update Batch Network
    # Creates or Updates multiple Networks
    # @param vbasoftware_database [String] Target database
    # @param networks [Array<Networks>] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(MultiCodeResponseListVBAResponse, Integer, Hash)>] MultiCodeResponseListVBAResponse data, response status code and response headers
    def create_or_update_batch_networks_with_http_info(vbasoftware_database, networks, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NetworksApi.create_or_update_batch_networks ...'
      end
      # verify the required parameter 'vbasoftware_database' is set
      if @api_client.config.client_side_validation && vbasoftware_database.nil?
        fail ArgumentError, "Missing the required parameter 'vbasoftware_database' when calling NetworksApi.create_or_update_batch_networks"
      end
      # verify the required parameter 'networks' is set
      if @api_client.config.client_side_validation && networks.nil?
        fail ArgumentError, "Missing the required parameter 'networks' when calling NetworksApi.create_or_update_batch_networks"
      end
      # resource path
      local_var_path = '/networks-batch'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['text/plain', 'application/json', 'text/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'text/json', 'application/*+json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'vbasoftware-database'] = vbasoftware_database

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(networks)

      # return_type
      return_type = opts[:debug_return_type] || 'MultiCodeResponseListVBAResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKeyAuth', 'bearerAuth']

      new_options = opts.merge(
        :operation => :"NetworksApi.create_or_update_batch_networks",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PUT, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NetworksApi#create_or_update_batch_networks\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete Network
    # Deletes a specific Network
    # @param vbasoftware_database [String] Target database
    # @param network_id [String] NetworkID
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def delete_network(vbasoftware_database, network_id, opts = {})
      delete_network_with_http_info(vbasoftware_database, network_id, opts)
      nil
    end

    # Delete Network
    # Deletes a specific Network
    # @param vbasoftware_database [String] Target database
    # @param network_id [String] NetworkID
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def delete_network_with_http_info(vbasoftware_database, network_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NetworksApi.delete_network ...'
      end
      # verify the required parameter 'vbasoftware_database' is set
      if @api_client.config.client_side_validation && vbasoftware_database.nil?
        fail ArgumentError, "Missing the required parameter 'vbasoftware_database' when calling NetworksApi.delete_network"
      end
      # verify the required parameter 'network_id' is set
      if @api_client.config.client_side_validation && network_id.nil?
        fail ArgumentError, "Missing the required parameter 'network_id' when calling NetworksApi.delete_network"
      end
      # resource path
      local_var_path = '/networks/{networkID}'.sub('{' + 'networkID' + '}', CGI.escape(network_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      header_params[:'vbasoftware-database'] = vbasoftware_database

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKeyAuth', 'bearerAuth']

      new_options = opts.merge(
        :operation => :"NetworksApi.delete_network",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NetworksApi#delete_network\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get Network
    # Gets a specific Network
    # @param vbasoftware_database [String] Target database
    # @param network_id [String] Network ID
    # @param [Hash] opts the optional parameters
    # @return [NetworksVBAResponse]
    def get_network(vbasoftware_database, network_id, opts = {})
      data, _status_code, _headers = get_network_with_http_info(vbasoftware_database, network_id, opts)
      data
    end

    # Get Network
    # Gets a specific Network
    # @param vbasoftware_database [String] Target database
    # @param network_id [String] Network ID
    # @param [Hash] opts the optional parameters
    # @return [Array<(NetworksVBAResponse, Integer, Hash)>] NetworksVBAResponse data, response status code and response headers
    def get_network_with_http_info(vbasoftware_database, network_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NetworksApi.get_network ...'
      end
      # verify the required parameter 'vbasoftware_database' is set
      if @api_client.config.client_side_validation && vbasoftware_database.nil?
        fail ArgumentError, "Missing the required parameter 'vbasoftware_database' when calling NetworksApi.get_network"
      end
      # verify the required parameter 'network_id' is set
      if @api_client.config.client_side_validation && network_id.nil?
        fail ArgumentError, "Missing the required parameter 'network_id' when calling NetworksApi.get_network"
      end
      # resource path
      local_var_path = '/networks/{networkID}'.sub('{' + 'networkID' + '}', CGI.escape(network_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['text/plain', 'application/json', 'text/json']) unless header_params['Accept']
      header_params[:'vbasoftware-database'] = vbasoftware_database

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'NetworksVBAResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKeyAuth', 'bearerAuth']

      new_options = opts.merge(
        :operation => :"NetworksApi.get_network",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NetworksApi#get_network\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List Networks
    # List all available Networks
    # @param vbasoftware_database [String] Target database
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page Page (default to 1)
    # @option opts [Integer] :page_size Page Size (default to 100)
    # @option opts [String] :sort_by Comma separated string to sort by. Each sort field can be followed by :asc or :desc to specify sort direction, ascending is default. E.g., &#39;Property1:desc,Property2:asc,Property3:asc&#39; sorts Property1 in descending order, Property2 in ascending, and Property3 in ascending.
    # @return [NetworksListVBAResponse]
    def list_networks(vbasoftware_database, opts = {})
      data, _status_code, _headers = list_networks_with_http_info(vbasoftware_database, opts)
      data
    end

    # List Networks
    # List all available Networks
    # @param vbasoftware_database [String] Target database
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page Page (default to 1)
    # @option opts [Integer] :page_size Page Size (default to 100)
    # @option opts [String] :sort_by Comma separated string to sort by. Each sort field can be followed by :asc or :desc to specify sort direction, ascending is default. E.g., &#39;Property1:desc,Property2:asc,Property3:asc&#39; sorts Property1 in descending order, Property2 in ascending, and Property3 in ascending.
    # @return [Array<(NetworksListVBAResponse, Integer, Hash)>] NetworksListVBAResponse data, response status code and response headers
    def list_networks_with_http_info(vbasoftware_database, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NetworksApi.list_networks ...'
      end
      # verify the required parameter 'vbasoftware_database' is set
      if @api_client.config.client_side_validation && vbasoftware_database.nil?
        fail ArgumentError, "Missing the required parameter 'vbasoftware_database' when calling NetworksApi.list_networks"
      end
      # resource path
      local_var_path = '/networks'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'pageSize'] = opts[:'page_size'] if !opts[:'page_size'].nil?
      query_params[:'sortBy'] = opts[:'sort_by'] if !opts[:'sort_by'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['text/plain', 'application/json', 'text/json']) unless header_params['Accept']
      header_params[:'vbasoftware-database'] = vbasoftware_database

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'NetworksListVBAResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKeyAuth', 'bearerAuth']

      new_options = opts.merge(
        :operation => :"NetworksApi.list_networks",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NetworksApi#list_networks\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update Network
    # Updates a specific Network
    # @param vbasoftware_database [String] Target database
    # @param network_id [String] NetworkID
    # @param networks [Networks] 
    # @param [Hash] opts the optional parameters
    # @return [NetworksVBAResponse]
    def update_network(vbasoftware_database, network_id, networks, opts = {})
      data, _status_code, _headers = update_network_with_http_info(vbasoftware_database, network_id, networks, opts)
      data
    end

    # Update Network
    # Updates a specific Network
    # @param vbasoftware_database [String] Target database
    # @param network_id [String] NetworkID
    # @param networks [Networks] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(NetworksVBAResponse, Integer, Hash)>] NetworksVBAResponse data, response status code and response headers
    def update_network_with_http_info(vbasoftware_database, network_id, networks, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: NetworksApi.update_network ...'
      end
      # verify the required parameter 'vbasoftware_database' is set
      if @api_client.config.client_side_validation && vbasoftware_database.nil?
        fail ArgumentError, "Missing the required parameter 'vbasoftware_database' when calling NetworksApi.update_network"
      end
      # verify the required parameter 'network_id' is set
      if @api_client.config.client_side_validation && network_id.nil?
        fail ArgumentError, "Missing the required parameter 'network_id' when calling NetworksApi.update_network"
      end
      # verify the required parameter 'networks' is set
      if @api_client.config.client_side_validation && networks.nil?
        fail ArgumentError, "Missing the required parameter 'networks' when calling NetworksApi.update_network"
      end
      # resource path
      local_var_path = '/networks/{networkID}'.sub('{' + 'networkID' + '}', CGI.escape(network_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['text/plain', 'application/json', 'text/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'text/json', 'application/*+json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'vbasoftware-database'] = vbasoftware_database

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(networks)

      # return_type
      return_type = opts[:debug_return_type] || 'NetworksVBAResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKeyAuth', 'bearerAuth']

      new_options = opts.merge(
        :operation => :"NetworksApi.update_network",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PUT, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: NetworksApi#update_network\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
