=begin
#VBASoftware

#APIs for VBASoftware

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module Vba
  class CarePlanScore
    attr_accessor :care_plan_score_key

    attr_accessor :care_plan_score_seq

    attr_accessor :care_plan_key

    attr_accessor :entry_date

    attr_accessor :entry_user

    attr_accessor :from_score

    attr_accessor :score_description

    attr_accessor :score_operator

    attr_accessor :thru_score

    attr_accessor :update_date

    attr_accessor :update_user

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'care_plan_score_key' => :'carePlanScore_Key',
        :'care_plan_score_seq' => :'carePlanScore_Seq',
        :'care_plan_key' => :'carePlan_Key',
        :'entry_date' => :'entry_Date',
        :'entry_user' => :'entry_User',
        :'from_score' => :'from_Score',
        :'score_description' => :'score_Description',
        :'score_operator' => :'score_Operator',
        :'thru_score' => :'thru_Score',
        :'update_date' => :'update_Date',
        :'update_user' => :'update_User'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'care_plan_score_key' => :'Integer',
        :'care_plan_score_seq' => :'Integer',
        :'care_plan_key' => :'Integer',
        :'entry_date' => :'Time',
        :'entry_user' => :'String',
        :'from_score' => :'Float',
        :'score_description' => :'String',
        :'score_operator' => :'String',
        :'thru_score' => :'Float',
        :'update_date' => :'Time',
        :'update_user' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'entry_user',
        :'from_score',
        :'score_description',
        :'score_operator',
        :'thru_score',
        :'update_user'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Vba::CarePlanScore` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Vba::CarePlanScore`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'care_plan_score_key')
        self.care_plan_score_key = attributes[:'care_plan_score_key']
      else
        self.care_plan_score_key = nil
      end

      if attributes.key?(:'care_plan_score_seq')
        self.care_plan_score_seq = attributes[:'care_plan_score_seq']
      else
        self.care_plan_score_seq = nil
      end

      if attributes.key?(:'care_plan_key')
        self.care_plan_key = attributes[:'care_plan_key']
      else
        self.care_plan_key = nil
      end

      if attributes.key?(:'entry_date')
        self.entry_date = attributes[:'entry_date']
      end

      if attributes.key?(:'entry_user')
        self.entry_user = attributes[:'entry_user']
      end

      if attributes.key?(:'from_score')
        self.from_score = attributes[:'from_score']
      end

      if attributes.key?(:'score_description')
        self.score_description = attributes[:'score_description']
      end

      if attributes.key?(:'score_operator')
        self.score_operator = attributes[:'score_operator']
      end

      if attributes.key?(:'thru_score')
        self.thru_score = attributes[:'thru_score']
      end

      if attributes.key?(:'update_date')
        self.update_date = attributes[:'update_date']
      end

      if attributes.key?(:'update_user')
        self.update_user = attributes[:'update_user']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @care_plan_score_key.nil?
        invalid_properties.push('invalid value for "care_plan_score_key", care_plan_score_key cannot be nil.')
      end

      if @care_plan_score_seq.nil?
        invalid_properties.push('invalid value for "care_plan_score_seq", care_plan_score_seq cannot be nil.')
      end

      if @care_plan_key.nil?
        invalid_properties.push('invalid value for "care_plan_key", care_plan_key cannot be nil.')
      end

      if !@entry_user.nil? && @entry_user.to_s.length > 20
        invalid_properties.push('invalid value for "entry_user", the character length must be smaller than or equal to 20.')
      end

      if !@score_description.nil? && @score_description.to_s.length > 512
        invalid_properties.push('invalid value for "score_description", the character length must be smaller than or equal to 512.')
      end

      if !@score_operator.nil? && @score_operator.to_s.length > 32
        invalid_properties.push('invalid value for "score_operator", the character length must be smaller than or equal to 32.')
      end

      if !@update_user.nil? && @update_user.to_s.length > 20
        invalid_properties.push('invalid value for "update_user", the character length must be smaller than or equal to 20.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @care_plan_score_key.nil?
      return false if @care_plan_score_seq.nil?
      return false if @care_plan_key.nil?
      return false if !@entry_user.nil? && @entry_user.to_s.length > 20
      return false if !@score_description.nil? && @score_description.to_s.length > 512
      return false if !@score_operator.nil? && @score_operator.to_s.length > 32
      return false if !@update_user.nil? && @update_user.to_s.length > 20
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] care_plan_score_key Value to be assigned
    def care_plan_score_key=(care_plan_score_key)
      if care_plan_score_key.nil?
        fail ArgumentError, 'care_plan_score_key cannot be nil'
      end

      @care_plan_score_key = care_plan_score_key
    end

    # Custom attribute writer method with validation
    # @param [Object] care_plan_score_seq Value to be assigned
    def care_plan_score_seq=(care_plan_score_seq)
      if care_plan_score_seq.nil?
        fail ArgumentError, 'care_plan_score_seq cannot be nil'
      end

      @care_plan_score_seq = care_plan_score_seq
    end

    # Custom attribute writer method with validation
    # @param [Object] care_plan_key Value to be assigned
    def care_plan_key=(care_plan_key)
      if care_plan_key.nil?
        fail ArgumentError, 'care_plan_key cannot be nil'
      end

      @care_plan_key = care_plan_key
    end

    # Custom attribute writer method with validation
    # @param [Object] entry_user Value to be assigned
    def entry_user=(entry_user)
      if !entry_user.nil? && entry_user.to_s.length > 20
        fail ArgumentError, 'invalid value for "entry_user", the character length must be smaller than or equal to 20.'
      end

      @entry_user = entry_user
    end

    # Custom attribute writer method with validation
    # @param [Object] score_description Value to be assigned
    def score_description=(score_description)
      if !score_description.nil? && score_description.to_s.length > 512
        fail ArgumentError, 'invalid value for "score_description", the character length must be smaller than or equal to 512.'
      end

      @score_description = score_description
    end

    # Custom attribute writer method with validation
    # @param [Object] score_operator Value to be assigned
    def score_operator=(score_operator)
      if !score_operator.nil? && score_operator.to_s.length > 32
        fail ArgumentError, 'invalid value for "score_operator", the character length must be smaller than or equal to 32.'
      end

      @score_operator = score_operator
    end

    # Custom attribute writer method with validation
    # @param [Object] update_user Value to be assigned
    def update_user=(update_user)
      if !update_user.nil? && update_user.to_s.length > 20
        fail ArgumentError, 'invalid value for "update_user", the character length must be smaller than or equal to 20.'
      end

      @update_user = update_user
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          care_plan_score_key == o.care_plan_score_key &&
          care_plan_score_seq == o.care_plan_score_seq &&
          care_plan_key == o.care_plan_key &&
          entry_date == o.entry_date &&
          entry_user == o.entry_user &&
          from_score == o.from_score &&
          score_description == o.score_description &&
          score_operator == o.score_operator &&
          thru_score == o.thru_score &&
          update_date == o.update_date &&
          update_user == o.update_user
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [care_plan_score_key, care_plan_score_seq, care_plan_key, entry_date, entry_user, from_score, score_description, score_operator, thru_score, update_date, update_user].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Vba.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
